# Generated by Django 4.2 on 2023-07-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
