# Generated by Django 4.2 on 2023-07-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial', '0002_user_public_key_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='public_key',
        ),
        migrations.AddField(
            model_name='user',
            name='public_key1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key2',
            field=models.TextField(null=True),
        ),
    ]
