# Generated by Django 4.2 on 2023-07-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial', '0005_document_file_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_txt',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
