# Generated by Django 4.2 on 2023-07-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial', '0006_alter_document_file_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nick',
        ),
        migrations.AlterField(
            model_name='document',
            name='sign',
            field=models.TextField(blank=True, null=True),
        ),
    ]
