# Generated by Django 4.2 on 2023-07-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inicial', '0007_remove_user_nick_alter_document_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='venue',
        ),
        migrations.RemoveField(
            model_name='vote_review',
            name='review',
        ),
        migrations.RemoveField(
            model_name='vote_review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Vote_Review',
        ),
    ]
